version: '3.9'
services:
  redis:
    container_name: redis
    image: redis:7
    restart: always

  nestapp:
    container_name: nestapp
    image: francescoxx/nestapp:1.0.0
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=ambujsingh
      - PG_PASSWORD=Zy1Wl2skAUZhgc4TEb9HVtHr0XYL4fO7
      - PG_DB=ambujsingh
      - PG_PORT=5432
      - PG_HOST=db


  db:
    container_name: db
    image: postgres:12
    environment:
      POSTGRES_USER: ambujsingh
      POSTGRES_PASSWORD: Zy1Wl2skAUZhgc4TEb9HVtHr0XYL4fO7
      POSTGRES_DB: ambujsingh
    ports:
      - '5433:5432' # Changed mapping to use host port 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
